# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: CIRCLE_BRANCH=$CIRCLE_BRANCH npm run build
      - persist_to_workspace:
          root: ./
          paths: 
            - build

  deploy:
    docker:
      - image: cibuilds/aws:1.15.44
    steps:
      - attach_workspace:
          at: ./client
      - run: aws configure set region us-west-2
      - run: aws configure set preview.cloudfront true
      - run: aws configure set preview.create-invalidation true
      - run: aws s3 sync client/build s3://pollenize/$CIRCLE_BRANCH --delete
      - run: aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"$AWS_CLOUDFRONT_ID\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":2,\"Items\":[\"/index.html\",\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
