# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/client
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: CIRCLE_BRANCH=$CIRCLE_BRANCH npm run build
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/client
    steps:
      - run: sudo pip install awscli
      - run: aws configure set region us-west-2
      - run: aws configure set preview.cloudfront true
      - run: aws configure set preview.create-invalidation true
      - run: aws s3 sync build s3://pollenize/$CIRCLE_BRANCH --delete
      - run: - aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"$AWS_CLOUDFRONT_ID\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":2,\"Items\":[\"/index.html\",\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
